# Turn an arbitrary file into a C source defining a byte array, so data can be
# compiled into the executable instead of shipped beside it.
#
# Used for the DXMA mission database: an AppImage / .exe / Flatpak that carries
# its own copy always works, whereas a loose CSV next to the binary is easy to
# lose in packaging and impossible to find reliably at runtime.
#
# Invoke at build time with:
#   cmake -DINPUT=<file> -DOUTPUT=<file.c> -DSYMBOL=<name> -P embed_file.cmake

if(NOT DEFINED INPUT OR NOT DEFINED OUTPUT OR NOT DEFINED SYMBOL)
	message(FATAL_ERROR "embed_file.cmake requires -DINPUT, -DOUTPUT and -DSYMBOL")
endif()

if(NOT EXISTS "${INPUT}")
	message(FATAL_ERROR "embed_file.cmake: input '${INPUT}' does not exist")
endif()

file(READ "${INPUT}" hex_content HEX)
string(LENGTH "${hex_content}" hex_len)
math(EXPR byte_count "${hex_len} / 2")

# Emit 0x.. bytes, 16 per line, so the generated file stays diff-able and does
# not blow up compiler line-length limits.
#
# Done with two bulk regex passes rather than a foreach over the bytes: for a
# ~360 KB input the loop version takes ~20s, this takes well under a second.
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," body "${hex_content}")
string(REGEX REPLACE "((0x..,){16})" "\\1\n\t" body "${body}")

get_filename_component(input_name "${INPUT}" NAME)

file(WRITE "${OUTPUT}"
"/* Generated by cmake/embed_file.cmake from ${input_name}. Do not edit. */\n"
"\n"
"const unsigned char ${SYMBOL}[] = {\n\t${body}\n};\n"
"const unsigned int ${SYMBOL}_len = ${byte_count}u;\n")
